# -*- coding: utf-8 -*-
"""credit_card_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPVfyeGmUiiczJKooyQa9ORai_lQsju8

# Credit Card Fraud Detection Project

This project detects fraudulent credit card transactions
using Machine Learning and Data Analysis techniques.

Features:
1. Data Cleaning
2. Exploratory Data Analysis
3. Fraud vs Non-Fraud Analysis
4. Data Visualization
5. Machine Learning Model Building
6. Fraud Prediction

Author: Disha Kataria
"""

# Import Libraries
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

# Load Dataset
df = pd.read_csv('creditcard.csv')

df

"""### Dataset Information"""

df.info()

# Missing Values Check
df.isnull().sum()

#Checking duplicate values
df.duplicated().sum()

"""##### Confidential data, so keeping the duplicates.

### Fraud vs Non-Fraud Count
"""

# Calculate the number of fraud and genuine transactions
fraud_transactions = df[df['Class'] == 1].shape[0]
fraud_transactions

genuine_transaction = df[df['Class']==0].shape[0]
genuine_transaction

fraud_percentage = (fraud_transactions/ df.shape[0])*100
fraud_percentage

df['Class'].value_counts(normalize=True)*100

# Fraud Distribution Visualization
sns.countplot(data = df, x='Class')
plt.title('Distribution of Class Variable')
plt.xlabel('Class (0: Genuine, 1: Fraud)')
plt.ylabel('Count')
plt.show()

plt.pie(df['Class'].value_counts(),labels=['Genuine','Fraud'], autopct='%1.2f%%')

from sklearn.preprocessing import StandardScaler

# Feature Scaling
scaler = StandardScaler()
df['Normalized_Amount'] = scaler.fit_transform(df['Amount'].values.reshape(-1,1))
#Standardization requires 2D data, therefore reshaped it.

df

x = df.drop(columns = ['Time', 'Amount', 'Class'])

x

y = df['Class']

y

# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.3,
                                                    random_state = 24 )

# Handle Imbalanced Dataset Using SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_sm, Y_train_sm = smote.fit_resample(x_train, y_train)

X_train_sm

Y_train_sm.value_counts()

"""## Decision Tree Model"""

decision_tree = DecisionTreeClassifier()

# Train Decision Tree Model
decision_tree.fit(X_train_sm, Y_train_sm)

# Decision Tree Prediction
dt_prediction = decision_tree.predict(x_test)

# Decision Tree Accuracy
dt_accuracy = accuracy_score(y_test, dt_prediction)
print(f"Decision Tree Accuracy : {dt_accuracy}")

# Decision Tree Classification Report
classificationReport = classification_report(y_test, dt_prediction)
print(classificationReport)

"""# Model Analysis

The Decision Tree model performs well on fraud detection.
Recall is important in fraud detection because identifying
fraudulent transactions is more critical than avoiding
some false positives.

# Random Forest Model
"""

# Train Random Forest Model
random_forest = RandomForestClassifier()
random_forest.fit(X_train_sm, Y_train_sm)

# Random Forest Prediction
rf_prediction = random_forest.predict(x_test)

# Random Forest Accuracy
rf_accuracy = accuracy_score(y_test, rf_prediction)
print(f"The accuracy achieved by random forest is {rf_accuracy}")

# Random Forest Classification Report
print(classification_report(y_test, rf_prediction))

"""# Random Forest Analysis

Random Forest performed better than the Decision Tree model.

Why Random Forest performed better:
- It combines multiple decision trees
- Reduces overfitting
- Gives more stable predictions
- Handles imbalanced datasets more effectively

Model Performance:
- High accuracy achieved
- Better fraud precision
- Good recall for fraud detection

In fraud detection, recall is very important because
missing fraudulent transactions can cause financial loss.

This model successfully identifies most fraudulent
transactions while maintaining strong overall performance.

# Logistic Regression
"""

log_model = LogisticRegression()

# Train Logistic Regression Model
log_model.fit(X_train_sm, Y_train_sm)

# Logistic Regression Prediction
log_prediction = log_model.predict(x_test)

# Logistic Regression Accuracy
log_accuracy = accuracy_score(y_test, log_prediction)
print(f"The accuracy achieved by logistic regression is {log_accuracy}")

# Logistic Regression Classification Report
print(classification_report(y_test, log_prediction))

"""# Logistic Regression Analysis

Logistic Regression is a simple and efficient
classification algorithm used for binary prediction problems.

In this project:
- The model was trained on balanced data using SMOTE
- It achieved good recall for fraud detection
- The model successfully identified many fraudulent transactions

However:
- Precision for fraud transactions is low
- This means the model produced more false positives

This happens because fraud datasets are highly imbalanced
and Logistic Regression is a simpler linear model.

Even though the overall accuracy is high,
accuracy alone is not enough in fraud detection.

Important Metrics in Fraud Detection:
- Recall → Detecting maximum fraud cases
- Precision → Reducing false fraud alerts
- F1-score → Balance between precision and recall

This model provides a good baseline for comparison
with advanced models like Decision Tree and Random Forest.

# SVM Model (Kernel : rbf)
"""

from sklearn.svm import SVC

svm_model = SVC(kernel = 'rbf')

# Train SVM Model
svm_model.fit(X_train_sm, Y_train_sm)

# SVM Model Prediction
svm_prediction = svm_model.predict(x_test)

# SVM Model Accuracy
svm_accuracy = accuracy_score(y_test, svm_prediction)
print(f"The accuracy achieved by SVM is {svm_accuracy}")

# SVM Model Classification Report
print(classification_report(y_test, svm_prediction))

"""# SVM Model Analysis

Support Vector Machine (SVM) is a powerful classification
algorithm used for both linear and non-linear problems.

In this project:
- SVM was used with the RBF (Radial Basis Function) kernel
- The model handled complex fraud patterns effectively
- It achieved high recall for fraud detection

Model Performance:
- Good overall accuracy
- Better fraud detection compared to Logistic Regression
- Improved balance between precision and recall

However:
- Precision is still lower than Random Forest
- Some false positive fraud predictions are generated

Why RBF Kernel is Used:
- It helps classify non-linear data
- Captures complex relationships between features
- Performs better on complicated datasets

Important Insight:
In fraud detection, detecting fraudulent transactions
(recall) is more important than only maximizing accuracy.

SVM performed better than Logistic Regression
but Random Forest still achieved the best overall results
in this project.

"""